const fs = require("fs");
const path = require("path");
const bt = String.fromCharCode(96);
const c = [];
c.push("import Database from 'better-sqlite3';");
c.push("import path from 'path';");
c.push("");
c.push("const DB_PATH = path.join(process.cwd(), 'data', 'phoebe.db');");
c.push("");
c.push("let db = null;");
c.push("");
c.push("export function getDb() {");
c.push("  if (!db) {");
c.push("    db = new Database(DB_PATH);");
c.push("    db.pragma('journal_mode = WAL');");
c.push("    db.pragma('foreign_keys = ON');");
c.push("    initDb(db);");
c.push("  }");
c.push("  return db;");
c.push("}");
c.push("");
c.push("function initDb(db) {");
c.push("  db.exec(" + bt + "    CREATE TABLE IF NOT EXISTS creators (");
c.push("      id INTEGER PRIMARY KEY AUTOINCREMENT,");
c.push("      username TEXT UNIQUE NOT NULL,");
c.push("      display_name TEXT,");
c.push("      avatar TEXT,");
c.push("      bio TEXT,");
c.push("      role TEXT DEFAULT 'creator',");
c.push("      created_at DATETIME DEFAULT CURRENT_TIMESTAMP");
c.push("    );");
c.push("");
c.push("    CREATE TABLE IF NOT EXISTS artworks (");
c.push("      id INTEGER PRIMARY KEY AUTOINCREMENT,");
c.push("      museum_id TEXT UNIQUE NOT NULL,");
c.push("      title TEXT NOT NULL,");
c.push("      title_en TEXT,");
c.push("      title_ja TEXT,");
c.push("      description TEXT,");
c.push("      creator_id INTEGER REFERENCES creators(id),");
c.push("      medium TEXT,");
c.push("      image_url TEXT,");
c.push("      world_line TEXT,");
c.push("      year TEXT DEFAULT '2026',");
c.push("      tags TEXT,");
c.push("      status TEXT DEFAULT 'approved',");
c.push("      featured INTEGER DEFAULT 0,");
c.push("      created_at DATETIME DEFAULT CURRENT_TIMESTAMP");
c.push("    );");
c.push("");
c.push("    CREATE TABLE IF NOT EXISTS timelines (");
c.push("      id INTEGER PRIMARY KEY AUTOINCREMENT,");
c.push("      slug TEXT UNIQUE NOT NULL,");
c.push("      name TEXT NOT NULL,");
c.push("      name_en TEXT,");
c.push("      name_ja TEXT,");
c.push("      description TEXT,");
c.push("      type TEXT,");
c.push("      cover_image TEXT,");
c.push("      creator_id INTEGER REFERENCES creators(id),");
c.push("      status TEXT DEFAULT 'approved',");
c.push("      created_at DATETIME DEFAULT CURRENT_TIMESTAMP");
c.push("    );");
c.push("");
c.push("    CREATE TABLE IF NOT EXISTS submissions (");
c.push("      id INTEGER PRIMARY KEY AUTOINCREMENT,");
c.push("      artwork_title TEXT NOT NULL,");
c.push("      creator_name TEXT NOT NULL,");
c.push("      medium TEXT,");
c.push("      image_path TEXT,");
c.push("      description TEXT,");
c.push("      source_link TEXT,");
c.push("      world_line TEXT,");
c.push("      status TEXT DEFAULT 'pending',");
c.push("      admin_notes TEXT,");
c.push("      created_at DATETIME DEFAULT CURRENT_TIMESTAMP");
c.push("    );");
c.push("");
c.push("    CREATE TABLE IF NOT EXISTS favorites (");
c.push("      id INTEGER PRIMARY KEY AUTOINCREMENT,");
c.push("      session_id TEXT NOT NULL,");
c.push("      artwork_id INTEGER REFERENCES artworks(id),");
c.push("      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,");
c.push("      UNIQUE(session_id, artwork_id)");
c.push("    );" + bt + ");");
c.push("");
c.push("  const count = db.prepare('SELECT COUNT(*) as count FROM creators').get();");
c.push("  if (count.count === 0) {");
c.push("    insertDefaultData(db);");
c.push("  }");
c.push("}");
c.push("");
c.push("function insertDefaultData(db) {");
c.push("  const insertCreator = db.prepare('INSERT INTO creators (username, display_name, bio, role) VALUES (?, ?, ?, ?');");
c.push("  insertCreator.run('museum', 'Museum Official', '菲比博物馆官方', 'admin');");
c.push("  insertCreator.run('artist01', 'Demo Artist 01', '专注于数字插画创作', 'creator');");
c.push("  insertCreator.run('artist02', 'Demo Artist 02', '擅长传统绘画风格', 'creator');");
c.push("  insertCreator.run('artist03', 'Demo Artist 03', '3D建模与渲染专家', 'creator');");
c.push("");
c.push("  const insertArtwork = db.prepare('INSERT INTO artworks (museum_id, title, title_en, title_ja, description, creator_id, medium, image_url, world_line, year, tags, featured) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?');");
c.push("  insertArtwork.run('PM-000001', '海上菲比', 'PHOEBE ON THE WILD SEA', '海のフィービー', '暴风来临前，菲比站在破旧的小船上，继续向未知海域前进。', 1, 'illustration', '/uploads/artworks/pm-000001.jpg', 'PIRATE PHOEBE', '2026', 'pirate,ocean,adventure', 1);");
c.push("  insertArtwork.run('PM-000002', '荒原航线', 'WILDERNESS ROUTE', '荒野航路', '在荒芜的原野上，菲比找到了一条被遗忘的航线。', 2, 'illustration', '/uploads/artworks/pm-000002.jpg', 'PIRATE PHOEBE', '2026', 'adventure,wilderness', 0);");
c.push("  insertArtwork.run('PM-000003', '深海来信', 'OCEAN WORLD', '深海からの手紙', '来自深海的一封信，承载着菲比的思念。', 3, 'illustration', '/uploads/artworks/pm-000003.jpg', 'OCEAN WORLD', '2026', 'ocean,letter', 0);");
c.push("  insertArtwork.run('PM-000004', '霓虹之下', 'UNDER NEON', 'ネオンの下で', '在霓虹灯闪烁的未来都市中，菲比寻找着自己的位置。', 4, '3d', '/uploads/artworks/pm-000004.jpg', 'CYBER PHOEBE', '2026', 'cyber,neon,future', 0);");
c.push("  insertArtwork.run('PM-000005', '校园午后', 'SCHOOL AFTERNOON', '学園の午後', '放学后的黄昏，校园里只剩下菲比一个人。', 2, 'illustration', '/uploads/artworks/pm-000005.jpg', 'SCHOOL PHOEBE', '2026', 'school,afternoon', 0);");
c.push("  insertArtwork.run('PM-000006', '未知档案', 'UNKNOWN ARCHIVE', '未知のアーカイブ', '一些无法解释的菲比。我们依然决定收藏她们。', 1, 'mixed', '/uploads/artworks/pm-000006.jpg', 'THE STRANGE ARCHIVE', '2026', 'strange,mystery', 0);");
c.push("");
c.push("  const insertTimeline = db.prepare('INSERT INTO timelines (slug, name, name_en, name_ja, description, type) VALUES (?, ?, ?, ?, ?, ?');");
c.push("  insertTimeline.run('pirate', '海盗菲比', 'PIRATE PHOEBE', '海賊フィービー', '暴风、木船、藏宝图与未知海域', 'community');");
c.push("  insertTimeline.run('school', '校园菲比', 'SCHOOL PHOEBE', '学園フィービー', '制服、校园、转学生、放学后的黄昏', 'community');");
c.push("  insertTimeline.run('cyber', '赛博菲比', 'CYBER PHOEBE', 'サイバーフィービー', '霓虹、机械、数据洪流与未来都市', 'community');");
c.push("  insertTimeline.run('fantasy', '幻想菲比', 'FANTASY PHOEBE', '幻想フィービー', '天使、堕天使、魔女、骑士与幻想王国', 'community');");
c.push("  insertTimeline.run('strange', '奇异档案', 'THE STRANGE ARCHIVE', '奇妙なアーカイブ', '一些无法解释的菲比', 'community');");
c.push("}");
fs.writeFileSync(path.join("D:", "dev", "Phoebe", "phoebe-museum", "src", "lib", "db", "index.ts"), c.join("\n"), "utf8");
console.log("Written " + c.length + " lines");