const fs = require("fs");
const path = require("path");
const bt = String.fromCharCode(96);
const c = [];
c.push("import Database from 'better-sqlite3';");
c.push("import path from 'path';");
c.push("");
c.push("const DB_PATH = path.join(process.cwd(), 'data', 'phoebe.db');");
c.push("");
c.push("let db;");
c.push("");
c.push("export function getDb() {");
c.push("  if (!db) {");
c.push("    db = new Database(DB_PATH);");
c.push("    db.pragma('journal_mode = WAL');");
c.push("    db.pragma('foreign_keys = ON');");
c.push("    initDb(db);");
c.push("  }");
c.push("  return db;");
c.push("}");
c.push("");
c.push("function initDb(db) {");
c.push("  db.exec(" + bt + "    CREATE TABLE IF NOT EXISTS creators (");
c.push("      id INTEGER PRIMARY KEY AUTOINCREMENT,");
c.push("      username TEXT UNIQUE NOT NULL,");
c.push("      display_name TEXT,");
c.push("      avatar TEXT,");
c.push("      bio TEXT,");
c.push("      role TEXT DEFAULT 'creator',");
c.push("      created_at DATETIME DEFAULT CURRENT_TIMESTAMP");
c.push("    );");
c.push("");
c.push("    CREATE TABLE IF NOT EXISTS artworks (");
c.push("      id INTEGER PRIMARY KEY AUTOINCREMENT,");
c.push("      museum_id TEXT UNIQUE NOT NULL,");
c.push("      title TEXT NOT NULL,");
c.push("      title_en TEXT,");
c.push("      title_ja TEXT,");
c.push("      description TEXT,");
c.push("      creator_id INTEGER REFERENCES creators(id),");
c.push("      medium TEXT,");
c.push("      image_url TEXT,");
c.push("      world_line TEXT,");
c.push("      year TEXT DEFAULT '2026',");
c.push("      tags TEXT,");
c.push("      status TEXT DEFAULT 'approved',");
c.push("      featured INTEGER DEFAULT 0,");
c.push("      created_at DATETIME DEFAULT CURRENT_TIMESTAMP");
c.push("    );");
c.push("");
c.push("    CREATE TABLE IF NOT EXISTS timelines (");
c.push("      id INTEGER PRIMARY KEY AUTOINCREMENT,");
c.push("      slug TEXT UNIQUE NOT NULL,");
c.push("      name TEXT NOT NULL,");
c.push("      name_en TEXT,");
c.push("      name_ja TEXT,");
c.push("      description TEXT,");
c.push("      type TEXT,");
c.push("      cover_image TEXT,");
c.push("      creator_id INTEGER REFERENCES creators(id),");
c.push("      status TEXT DEFAULT 'approved',");
c.push("      created_at DATETIME DEFAULT CURRENT_TIMESTAMP");
c.push("    );");
c.push("");
c.push("    CREATE TABLE IF NOT EXISTS submissions (");
c.push("      id INTEGER PRIMARY KEY AUTOINCREMENT,");
c.push("      artwork_title TEXT NOT NULL,");
c.push("      creator_name TEXT NOT NULL,");
c.push("      medium TEXT,");
c.push("      image_path TEXT,");
c.push("      description TEXT,");
c.push("      source_link TEXT,");
c.push("      world_line TEXT,");
c.push("      status TEXT DEFAULT 'pending',");
c.push("      admin_notes TEXT,");
c.push("      created_at DATETIME DEFAULT CURRENT_TIMESTAMP");
c.push("    );");
c.push("");
c.push("    CREATE TABLE IF NOT EXISTS favorites (");
c.push("      id INTEGER PRIMARY KEY AUTOINCREMENT,");
c.push("      session_id TEXT NOT NULL,");
c.push("      artwork_id INTEGER REFERENCES artworks(id),");
c.push("      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,");
c.push("      UNIQUE(session_id, artwork_id)");
c.push("    );" + bt + ");");
c.push("  }");
fs.writeFileSync(path.join("D:", "dev", "Phoebe", "phoebe-museum", "src", "lib", "db", "index.ts"), c.join("\n"), "utf8");
console.log("Written");